update ups.py for python < 2.7 support
fix this error for python 2.6:

$ ./test.py
Status: Success tracking: 1ZR052A2D491648028, cost: 127.89
Status: Success tracking: 1ZR052A2D497605830, cost: 127.89
UPS Error 250065: Invalid or missing request element
Traceback (most recent call last):
  File "./test.py", line 338, in <module>
    TestUPS()
  File "./test.py", line 74, in TestUPS
    response = u.label(packages, shipper, r, ups.SERVICES[2][0], ups.PACKAGES[7][0], validate, [ 'test@mytrashmail.com '])
  File "/python-ship/ups.py", line 323, in label
    shipment = self._create_shipment(client, packages, shipper_address, recipient_address, box_shape, create_reference_number=create_reference_number, can_add_delivery_confirmation=delivery_confirmation)
  File "/python-ship/ups.py", line 179, in _create_shipment
    reference_number = client.factory.create('{}:ReferenceNumberType'.format(namespace))
ValueError: zero length field name in format